const villages={kankroli:{name:"Kankroli",district:"Rajsamand",state:"Rajasthan"},bhambora:{name:"Bhambora",district:"Ajmer",state:"Rajasthan"},chandpur:{name:"Chandpur",district:"Sikar",state:"Rajasthan"}};
const journeys={
 wheat:{name:"Gehu",icon:"🌾",intro:"Roti tak pahunchne se pehle gehu ka safar khet se shuru hota hai.",steps:[["🌱","Beej","Kisan achhe beej ko mitti mein lagata hai."],["🌾","Khet","Paani, mitti, dhoop aur mehnat se fasal badhti hai."],["🚜","Katai","Fasal pakne par katai hoti hai aur gehu ikattha kiya jata hai."],["🏪","Mandi","Anaj mandi tak pahunchta hai, jahan uska agla safar shuru hota hai."],["🏠","Ghar / Chakki","Gehu saaf hokar pisai ke liye jata hai aur aata banta hai."],["🍞","Plate","Aakhir mein wahi gehu roti ban kar shehar aur gaon ki plate tak pahunchta hai."]]},
 milk:{name:"Doodh",icon:"🥛",intro:"Ek glass doodh ke peeche pashu, parivaar aur roz ki mehnat hoti hai.",steps:[["🐄","Pashu","Gaon ke parivaar apne pashuon ki dekhbhal karte hain."],["🥛","Doodh Nikalna","Subah aur shaam doodh nikala jata hai."],["🧺","Collection","Doodh collection point ya dairy tak pahunchta hai."],["🏭","Dairy","Doodh ki testing aur processing ke baad supply hoti hai."],["🚚","Safar","Doodh gaadiyon ke zariye shehar ki taraf jata hai."],["🏙️","Shehar","Aakhir mein doodh ghar, chai aur kitchen tak pahunchta hai."]]},
 vegetable:{name:"Sabzi",icon:"🥕",intro:"Shehar ki sabzi mandi tak pahunchne se pehle sabzi ka safar khet mein hota hai.",steps:[["🌱","Beej / Paudha","Kisan season ke hisaab se sabzi ka beej ya paudha lagata hai."],["💧","Paani & Dekhbhal","Sinchai, ghaas saaf karna aur paudhe ki dekhbhal hoti hai."],["🥕","Tudai","Sabzi tayyar hone par khet se todhi jati hai."],["🧺","Sorting","Sabzi ko saaf karke quality aur size ke hisaab se taiyar kiya jata hai."],["🏪","Mandi","Sabzi mandi mein aati hai aur traders/retailers tak pahunchti hai."],["🏙️","Shehar ki Rasoi","Aakhir mein sabzi market se ghar aur kitchen tak pahunchti hai."]]}
};
const app=document.querySelector("#app");
function nav(){return `<header class="topbar"><div class="shell nav"><button class="brand" id="home">Village<span>Deko</span></button><button class="pill" id="explore">Explore</button></div></header>`}
function home(){app.innerHTML=`${nav()}<main class="shell"><section class="hero"><div class="hero-main"><div class="eyebrow">FOOD JOURNEY</div><h1>Khaana kahan se aata hai?</h1><p>Gaon ke khet aur pashuon se lekar shehar ki plate tak — food ka poora safar samjho.</p></div></section><section class="section"><div class="section-head"><div><h2>Ek safar choose karo</h2><div class="muted">Kisi food ki journey enter karo</div></div></div><div class="journey-grid">${Object.entries(journeys).map(([id,j])=>`<button class="jcard" data-id="${id}"><div class="jicon">${j.icon}</div><h3>${j.name}</h3><p>${j.intro}</p><span>Journey shuru karo →</span></button>`).join("")}</div></section><section class="why"><div class="eyebrow">VILLAGEDEKO KA MAQSAD</div><h2>Jo khaana shehar mein dikhta hai, uski kahani gaon se shuru hoti hai.</h2><p>Isliye VillageDeko par hum sirf photo nahi dikhayenge — uske peeche ki zindagi bhi samjhayenge.</p></section></main>`;document.querySelectorAll(".jcard").forEach(x=>x.onclick=()=>journey(x.dataset.id));document.querySelector("#home").onclick=home;document.querySelector("#explore").onclick=home}
function journey(id,villageId=null){const j=journeys[id];let active=0;app.innerHTML=`${nav()}<main class="shell journey-page"><button class="back" id="back">← Food Journey par wapas</button><section class="journey-head"><div class="bigicon">${j.icon}</div><div><div class="eyebrow">FOOD JOURNEY</div><h1>${j.name}</h1><p>${j.intro}</p></div></section><div class="route" id="route">${j.steps.map((s,i)=>`<article class="step ${i===0?"active":""}" data-i="${i}"><div class="step-number">${i+1}</div><div class="step-icon">${s[0]}</div><div class="step-content"><div class="eyebrow">STEP ${i+1} OF ${j.steps.length}</div><h2>${s[1]}</h2><p>${s[2]}</p><button class="next">${i===j.steps.length-1?"Journey Complete":"Next Step →"}</button></div></article>`).join("")}</div><div class="journey-end" id="end" hidden><div class="bigicon">❤️</div><div><div class="eyebrow">JOURNEY COMPLETE</div><h2>Ab aap is khaane ki kahani jaante hain.</h2><p>Gaon ki mehnat se shehar ki plate tak — har bite ke peeche ek safar hai.</p><button class="primary" id="again">Phir Se Dekho</button></div></div></main>`;document.querySelector("#back").onclick=()=>village(villageId||"kankroli");document.querySelector("#home").onclick=home;document.querySelector("#explore").onclick=home;const steps=[...document.querySelectorAll(".step")];function activate(i){steps.forEach((s,k)=>s.classList.toggle("active",k===i));steps[i].scrollIntoView({behavior:"smooth",block:"center"})}steps.forEach((s,i)=>s.querySelector(".next").onclick=()=>{if(i<steps.length-1)activate(i+1);else{document.querySelector("#end").hidden=false;document.querySelector("#end").scrollIntoView({behavior:"smooth"})}});document.querySelector("#again").onclick=()=>{document.querySelector("#end").hidden=true;activate(0)}}
home();