import { collection, addDoc, getDocs, getDoc, deleteDoc, doc, updateDoc, setDoc, serverTimestamp, query, where, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { db, auth } from "./firebase-config.js";
import { CLOUDINARY_CLOUD_NAME, CLOUDINARY_UPLOAD_PRESET } from "./media-config.js";

const $=id=>document.getElementById(id), uid=()=>currentUser?.uid||null;
let currentUser=null,villages=[],currentVillage=null,currentVillageTab="overview",previousView="homeView",activityRows=[],packageRows=[];
const STATES=["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Jammu and Kashmir","Ladakh","Lakshadweep","Puducherry"];
const DAY=[['05:30','🌅','Village Morning','Sunrise, fresh air and the first rhythm of the village.'],['06:00','🐄','Dairy & Animals','Feeding animals, milking and the morning routine.'],['07:00','🌾','Fields','Walk into the fields and learn what is growing.'],['09:00','☕','Tea & Breakfast','A local breakfast and the stories around it.'],['11:00','🛠️','Village Work','Craft, farming, household and local work.'],['13:00','🍲','Home Food','Understand the meal and where its ingredients came from.'],['15:00','🌤️','Afternoon','Rest, shade, water and slower village life.'],['17:00','🏡','Village Life','Walks, local market, children and everyday life.'],['19:00','🛕','Temple & Culture','Temple, bhajan, folk music or a local tradition.'],['21:00','🌙','Village Night','A quiet night and a different sky.']];
const FOOD=[['🌾','Wheat','Seed → Field → Sowing → Water → Crop → Harvest → Mandi → Mill → Flour → Roti'],['🥬','Vegetables','Seed → Field → Water → Crop Care → Harvest → Sorting → Market → Home → Plate'],['🥛','Milk','Animal → Milking → Collection → Transport → Processing → Home → Cup / Plate'],['🫘','Dal','Seed → Field → Harvest → Cleaning → Milling → Market → Home → Plate'],['🌶️','Spices','Crop → Harvest → Drying → Cleaning → Processing → Market → Kitchen → Plate']];
const CULTURE=[['🎵','Folk Music','Songs, instruments and traditions carried through generations.'],['🥁','Local Instruments','Meet the makers and players behind rural sounds.'],['🛕','Bhajan & Temple Life','Understand local worship, stories and traditions.'],['🎉','Festivals','See how villages celebrate seasons and community life.'],['💍','Marriage Traditions','Discover local wedding customs and food.'],['👗','Traditional Clothing','Regional dress, craft and meaning.'],['🎨','Local Art','Crafts, painting, textiles and handmade work.'],['🧓','Old Stories','Buzurgon se suno — memories in the local voice.']];
const FARM=[['🌱','Land & Seed','How land is prepared and why the right seed matters.'],['🌾','Sowing','How farmers plant a crop and plan the season.'],['💧','Water','Why crops need water and how farmers manage it.'],['🌿','Crop Care','How farmers protect and grow a crop.'],['🚜','Farm Work','People, tools and machines in the field.'],['🧺','Harvest & Mandi','How the crop moves from field to market.'],['🍞','Food','How farming finally becomes food on our plate.']];
const CHALLENGES=[['🌅','Best Village Sunrise','A beautiful original sunrise from a real village.'],['🌾','Best Farming Story','A useful story from a farmer or farming family.'],['🍲','Best Local Food','A traditional dish with its village story.'],['🎵','Best Folk Culture','Music, dance, instrument or tradition.'],['📸','Old vs New Village','A meaningful old-and-current comparison.'],['🎉','Best Festival Story','A festival explained by the people who live it.']];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function requireLogin(){if(!currentUser){openModal('loginModal');return false}return true}
function openModal(id){$(id)?.classList.add('is-open');document.body.style.overflow='hidden'} function closeModal(id){$(id)?.classList.remove('is-open');document.body.style.overflow=''}
function setActiveNav(key){document.querySelectorAll('.nav-scroll [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===key));const a=document.querySelector(`.nav-scroll [data-nav=\"${key}\"]`);a?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}
function showView(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function goHome(){showView('homeView');setActiveNav('home');loadHome()} function goBackFromVillage(){showView(previousView)}
function openExplore(){showView('exploreView');setActiveNav('explore');renderStates();renderVillageCards(villages,$('exploreVillages'))}
function openExperience(){showView('experienceView');setActiveNav('experiences');renderDay();renderVillageCards(villages.filter(v=>(v.activities||[]).length),$('experienceVillages'))}
function openVisit(){showView('visitView');setActiveNav('trips');renderVillageCards(villages.filter(v=>v.stayAvailable||v.hostName||v.activities?.length),$('visitVillages'))}
function openFood(){showView('foodView');renderFood()} function openPeople(){showView('peopleView');loadPeople()}
function openCulture(){showView('cultureView');renderCulture()} function openStories(){showView('storiesView');setActiveNav('stories');loadStories()}
function openFarming(){showView('farmingView');renderFarming()} function openMarket(){showView('marketView');loadMarket()}
function openChallenges(){showView('challengeView');renderChallenges()} function openWedding(){showView('weddingView');loadWeddingEvents();}
function openSearch(){document.querySelector('.search-box input')?.focus()}
function openProfile(){showView('profileView');renderProfile()}
function openListVillage(){if(!requireLogin())return;resetListingForm();openModal('listVillageModal')}
function openPostModal(){if(!requireLogin())return;populateVillageSelect();openModal('postModal')}
function openMediaUploader(){if(!requireLogin()||!currentVillage)return;openModal('mediaModal')}
function openProductModal(){if(!requireLogin())return;openModal('productModal')}
function openBusinessModal(){if(!requireLogin())return;openModal('businessModal')}
function fillStates(){for(const id of ['stateSelect','lvState']){const s=$(id);if(!s)continue;const first=s.options[0];s.innerHTML='';if(first)s.appendChild(first);STATES.forEach(st=>{const o=document.createElement('option');o.value=st;o.textContent=st;s.appendChild(o)})}$('stateCount').textContent=STATES.length}
function renderStates(){const emojis=['🌴','🏜️','🏔️','🌾','🌊','🌿'];$('statesGrid').innerHTML=STATES.map((s,i)=>`<button class="state-card" onclick="selectState('${esc(s)}')"><span>${emojis[i%emojis.length]}</span><b>${esc(s)}</b><small>Explore villages →</small></button>`).join('')}
function selectState(state){if(!state){openExplore();return}previousView='exploreView';showView('stateView');$('stateTitle').textContent=state;$('stateSubtitle').textContent=`${state} — listed villages, experiences and stays` ;renderVillageCards(villages.filter(v=>v.vState===state),$('stateVillages'))}
function filterVillages(term){const q=term.toLowerCase().trim();const list=!q?villages:villages.filter(v=>[v.vName,v.vDistrict,v.vState,v.vDescription,...(v.activities||[]).map(a=>a.name)].join(' ').toLowerCase().includes(q));if(!$('homeView').classList.contains('hidden'))renderVillageCards(list.slice(0,12),$('homeVillages'));else if(!$('exploreView').classList.contains('hidden'))renderVillageCards(list,$('exploreVillages'))}
function villageCard(v){const img=v.images?.[0];return `<article class="village-card" onclick="openVillage('${esc(v.id)}')">${img?`<img class="village-cover" src="${esc(img)}" loading="lazy">`:'<div class="village-cover placeholder">🏡</div>'}<div class="village-card-body"><div class="location">📍 ${esc(v.vName)} · ${esc(v.vDistrict)} · ${esc(v.vState)}</div><h3>${esc(v.vName)}</h3><p class="muted">${esc(v.vDescription||'Experience village life with local hosts.')}</p><div class="pill-row">${(v.activities||[]).slice(0,4).map(a=>`<span class="pill">${esc(a.name)}</span>`).join('')}</div><div class="card-footer"><span class="price">${v.basePrice?`From ₹${esc(v.basePrice)}`:'Host priced'}</span><span class="text-btn">View profile →</span></div></div></article>`}
function renderVillageCards(list,c){if(!c)return;c.innerHTML=list.length?list.map(villageCard).join(''):'<div class="empty">No villages listed here yet.</div>'}
async function loadVillages(){try{const snap=await getDocs(collection(db,'villagesListings'));villages=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));loadHome()}catch(e){console.error(e);toast('Could not load villages. Check Firebase rules.')}}
function loadHome(){renderVillageCards(villages.slice(0,12),$('homeVillages'));$('villageCount').textContent=villages.length;$('experienceCount').textContent=villages.reduce((n,v)=>n+(v.activities?.length||0),0)}
async function openVillage(id){currentVillage=villages.find(v=>v.id===id);if(!currentVillage)return;previousView=$('stateView').classList.contains('hidden')?'exploreView':'stateView';currentVillageTab='overview';showView('villageView');renderVillageHeader();renderVillageTabs();await renderVillageContent()}
function renderVillageHeader(){const v=currentVillage;const img=v.images?.[0];$('villageHeader').innerHTML=`<div class="village-profile-cover">${img?`<img src="${esc(img)}">`:''}<div class="cover-gradient"></div><div class="village-profile-info"><div class="avatar">🌾</div><div><h2>${esc(v.vName)}</h2><p>📍 ${esc(v.vDistrict)} · ${esc(v.vState)}</p><p>${esc(v.hostName||'Local host')} · ${(v.images||[]).length} media</p></div></div></div>`}
const tabs=[['overview','🏡 Overview'],['media','📸 Photos & Videos'],['activities','🎯 Activities'],['day','🌅 A Day'],['food','🌾 Food Journey'],['people','👨‍🌾 People'],['culture','🎵 Culture'],['stories','🎥 Stories'],['farming','🌱 Learn Farming'],['visit','🧳 Visit']];
function renderVillageTabs(){$('villageTabs').innerHTML=tabs.map(([id,label])=>`<button class="vtab ${currentVillageTab===id?'active':''}" onclick="setVillageTab('${id}')">${label}</button>`).join('')}
function setVillageTab(t){currentVillageTab=t;renderVillageTabs();renderVillageContent()}
async function renderVillageContent(){const c=$('villageContent'),v=currentVillage;if(currentVillageTab==='overview'){c.innerHTML=`<div class="content-card"><h2>Experience ${esc(v.vName)}</h2><p class="muted">${esc(v.vDescription||'A real village experience.')}</p><div class="section-grid"><div class="mini-card"><h3>🏡 Stay</h3><p>${v.stayAvailable?'Homestay available':'Ask the host about stay options.'}</p></div><div class="mini-card"><h3>👤 Host</h3><p>${esc(v.hostName||'Local host')} · ${esc(v.hostWhatsapp||'Contact through enquiry')}</p></div><div class="mini-card"><h3>🎯 Activities</h3><p>${v.activities?.length||0} host-listed experiences.</p></div><div class="mini-card"><h3>📍 Destination</h3><p>${esc(v.vDistrict)}, ${esc(v.vState)}</p></div></div></div><div class="host-cta"><div><b>Plan your village visit</b><p>Choose an activity and send an enquiry at the host-set price.</p></div><button class="primary" onclick="setVillageTab('activities')">View experiences</button></div>`}else if(currentVillageTab==='media'){renderMedia(c,v)}else if(currentVillageTab==='activities'){renderActivities(c,v)}else if(currentVillageTab==='day'){renderDay(c)}else if(currentVillageTab==='food'){renderFood(c)}else if(currentVillageTab==='people'){await renderVillagePeople(c,v)}else if(currentVillageTab==='culture'){renderCulture(c,v)}else if(currentVillageTab==='stories'){await renderVillageStories(c,v)}else if(currentVillageTab==='farming'){renderFarming(c)}else if(currentVillageTab==='visit'){renderVisitVillage(c,v)}}
function renderMedia(c,v){const media=(v.media||[]);const oldImgs=(v.images||[]).map(url=>({url,type:'image'}));const oldVids=(v.videos||[]).map(url=>({url,type:'video'}));const all=[...oldImgs,...oldVids,...media.filter(m=>!oldImgs.some(x=>x.url===m.url)&&!oldVids.some(x=>x.url===m.url))];c.innerHTML=`<div class="content-card"><h2>Photos & Videos</h2><p class="muted">Real media added by the village host.</p>${all.length?`<div class="media-grid">${all.map(m=>m.type==='video'?`<video src="${esc(m.url)}" controls preload="metadata"></video>`:m.type==='audio'?`<div class="mini-card"><b>🎙️ Local Voice</b><audio src="${esc(m.url)}" controls style="width:100%;margin-top:10px"></audio></div>`:`<img src="${esc(m.url)}" loading="lazy" onclick="openImage('${esc(m.url)}')">`).join('')}</div>`:'<div class="empty">The host has not added media yet.</div>'}</div>${v.ownerUid===uid()?'<div class="host-cta"><div><b>Add more photos or videos</b><p>Keep the village profile alive with fresh media.</p></div><button class="primary" onclick="openMediaUploader()">＋ Add media</button></div>':''}`}
function renderActivities(c,v){const acts=v.activities||[];c.innerHTML=`<div class="content-card"><h2>Activities</h2><p class="muted">The host sets the price and availability for every experience.</p><div class="section-grid">${acts.map(a=>`<div class="mini-card"><h3>${esc(a.name)}</h3><div class="booking-price">${a.price?`₹${esc(a.price)}`:'On enquiry'}</div><p>${esc(a.description||'Local host-led experience.')}</p><button class="primary" onclick="openBooking('${esc(v.id)}','${esc(a.name)}')">Plan this experience</button></div>`).join('')||'<div class="empty">No activities listed yet.</div>'}</div></div>`}
function renderDay(c=$('dayTimeline')){if(!c)return;c.innerHTML=DAY.map((m,i)=>`<div class="moment"><div class="moment-time">${m[0]}</div><div class="moment-dot"><span>${m[1]}</span>${i<DAY.length-1?'<i></i>':''}</div><div class="moment-copy"><b>${m[2]}</b><p>${m[3]}</p></div></div>`).join('')}
function renderFood(c=$('foodGrid')){if(!c)return;c.innerHTML=FOOD.map(x=>`<article class="story-card"><h3>${x[0]} ${x[1]}</h3><p>${x[2]}</p><span class="pill">Real village stages can be attached here</span></article>`).join('')}
async function loadPeople(){const c=$('peopleGrid');const people=[];try{const snap=await getDocs(collection(db,'people'));snap.docs.forEach(d=>people.push(d.data()))}catch{}c.innerHTML=(people.length?people:[{name:'Farmer',role:'Kisan',village:'VillageDeko villages',story:'Real farmers explain the land, crop and season.'},{name:'Local Cook',role:'Food & Tradition',village:'VillageDeko villages',story:'Local families preserve recipes and food traditions.'},{name:'Village Artisan',role:'Craft',village:'VillageDeko villages',story:'Learn a craft directly from the person who makes it.'},{name:'Village Elder',role:'Memory Keeper',village:'VillageDeko villages',story:'Old village memories and changes across generations.'}]).map(p=>`<article class="story-card"><h3>👤 ${esc(p.name)}</h3><p><b>${esc(p.role)}</b> · ${esc(p.village)}</p><p>${esc(p.story)}</p></article>`).join('')}
function renderCulture(c=$('cultureGrid'),v=null){if(!c)return;c.innerHTML=(v?.culture?.length?v.culture.map(x=>["🎵",x,'A local cultural experience listed by the host.']):CULTURE).map(x=>`<article class="culture-card"><div style="font-size:26px">${x[0]}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('')}
async function loadStories(){const c=$('storiesGrid');let stories=[];try{const snap=await getDocs(query(collection(db,'villageStories'),orderBy('createdAt','desc')));stories=snap.docs.map(d=>d.data())}catch{}c.innerHTML=stories.length?stories.map(storyCard).join(''):'<div class="empty">Village stories will appear here as hosts and contributors add them.</div>'}
function storyCard(s){return `<article class="story-card">${s.mediaUrl?`<img class="product-photo" src="${esc(s.mediaUrl)}">`:''}<h3>${esc(s.title||'Village Story')}</h3><p>${esc(s.person||'Local person')} · ${esc(s.villageName||'Village')}</p><p>${esc(s.text||'')}</p></article>`}
async function renderVillageStories(c,v){let stories=[];try{const snap=await getDocs(query(collection(db,'villageStories'),where('villageId','==',v.id)));stories=snap.docs.map(d=>d.data())}catch{}c.innerHTML=`<div class="story-grid">${stories.length?stories.map(storyCard).join(''):'<div class="empty">No stories added yet.</div>'}</div>`}
function renderFarming(c=$('farmingGrid')){if(!c)return;c.innerHTML=FARM.map(x=>`<article class="story-card"><h3>${x[0]} ${x[1]}</h3><p>${x[2]}</p></article>`).join('')}
function renderVisitVillage(c,v){c.innerHTML=`<div class="content-card"><h2>Visit ${esc(v.vName)}</h2><p class="muted">Choose from host-listed experiences, stays and packages.</p><div class="section-grid">${(v.packages||[]).map(p=>`<div class="mini-card"><h3>📦 ${esc(p.name)}</h3><div class="booking-price">${p.price?`₹${esc(p.price)}`:'On enquiry'}</div><p>${esc(p.description||'')} · ${esc(p.days||'')} day(s)</p><button class="primary" onclick="openBooking('${esc(v.id)}','${esc(p.name)}')">Enquire</button></div>`).join('')||'<div class="empty">No packages listed yet.</div>'}</div></div>`}
async function renderVillagePeople(c,v){let people=v.people||[];if(!people.length)people=[{name:'Village people',role:'Local community',story:'The host can add farmers, elders, cooks, artisans and other people here.'}];c.innerHTML=`<div class="story-grid">${people.map(p=>`<article class="story-card"><h3>👤 ${esc(p.name||'Local person')}</h3><p><b>${esc(p.role||'Village resident')}</b></p><p>${esc(p.story||'')}</p></article>`).join('')}</div>`}
function openImage(url){const c=$('genericBody');$('genericTitle').textContent='Village Media';c.innerHTML=`<img src="${esc(url)}" style="width:100%;border-radius:16px" alt="Village media">`;openModal('genericModal')}
function populateVillageSelect(){const s=$('postVillage');s.innerHTML='<option value="">Select village</option>'+villages.map(v=>`<option value="${esc(v.id)}">${esc(v.vName)} — ${esc(v.vDistrict)}, ${esc(v.vState)}</option>`).join('')}
function addActivityRow(data={}){activityRows.push({...data});renderActivityRows()}function renderActivityRows(){const c=$('activityRows');if(!c)return;c.innerHTML=activityRows.map((a,i)=>`<div class="repeat-row"><input class="input" value="${esc(a.name||'')}" oninput="activityRows[${i}].name=this.value" placeholder="Activity name"><input class="input" value="${esc(a.price||'')}" oninput="activityRows[${i}].price=this.value" placeholder="Price"><input class="input" value="${esc(a.description||'')}" oninput="activityRows[${i}].description=this.value" placeholder="Details"><button type="button" class="remove-btn" onclick="activityRows.splice(${i},1);renderActivityRows()">×</button></div>`).join('')}
function addPackageRow(data={}){packageRows.push({...data});renderPackageRows()}function renderPackageRows(){const c=$('packageRows');if(!c)return;c.innerHTML=packageRows.map((p,i)=>`<div class="repeat-row"><input class="input" value="${esc(p.name||'')}" oninput="packageRows[${i}].name=this.value" placeholder="Package name"><input class="input" value="${esc(p.days||'')}" oninput="packageRows[${i}].days=this.value" placeholder="Days"><input class="input" value="${esc(p.price||'')}" oninput="packageRows[${i}].price=this.value" placeholder="Price"><button type="button" class="remove-btn" onclick="packageRows.splice(${i},1);renderPackageRows()">×</button></div>`).join('')}
function resetListingForm(){activityRows.length=0;packageRows.length=0;$('listVillageForm')?.reset();renderActivityRows();renderPackageRows()}
async function uploadToCloudinary(file,folder='media'){if(!file)throw new Error('No file');if(!CLOUDINARY_CLOUD_NAME||!CLOUDINARY_UPLOAD_PRESET)throw new Error('Cloudinary configuration missing.');const type=file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'image';const fd=new FormData();fd.append('file',file);fd.append('upload_preset',CLOUDINARY_UPLOAD_PRESET);fd.append('folder',`villagedeko/${folder}/${uid()}`);const r=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(CLOUDINARY_CLOUD_NAME)}/auto/upload`,{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.secure_url)throw new Error(d.error?.message||'Cloudinary upload failed');return {url:d.secure_url,type}};
async function uploadMany(files,folder){const out=[];for(const f of files)out.push(await uploadToCloudinary(f,folder));return out}
async function saveVillageListing(e){e.preventDefault();if(!requireLogin())return;const btn=$('listVillageBtn');btn.disabled=true;try{const media=await uploadMany([...($('lvMedia').files||[])],'villages');const data={ownerUid:uid(),hostName:$('lvHost').value.trim(),hostWhatsapp:$('lvWhatsapp').value.trim(),vName:$('lvName').value.trim(),vDistrict:$('lvDistrict').value.trim(),vState:$('lvState').value,vDescription:$('lvDescription').value.trim(),media,images:media.filter(x=>x.type==='image').map(x=>x.url),videos:media.filter(x=>x.type==='video').map(x=>x.url),activities:activityRows.filter(x=>x.name),packages:packageRows.filter(x=>x.name),culture:$('lvCulture').value.split(',').map(x=>x.trim()).filter(Boolean),people:[],stayAvailable:packageRows.length>0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await addDoc(collection(db,'villagesListings'),data);closeModal('listVillageModal');await loadVillages();toast('Village listed successfully.')}catch(err){toast(err.message)}finally{btn.disabled=false}}
async function publishVillageContent(e){e.preventDefault();if(!requireLogin())return;const v=villages.find(x=>x.id===$('postVillage').value);if(!v)return;try{const media=await uploadMany([...($('postMedia').files||[])],'stories');const common={ownerUid:uid(),villageId:v.id,villageName:v.vName,vDistrict:v.vDistrict,vState:v.vState,title:$('postTitle').value.trim(),person:$('postPerson').value.trim(),text:$('postText').value.trim(),type:$('postType').value,createdAt:serverTimestamp()};if(media.length){common.mediaUrl=media[0].url;common.mediaType=media[0].type}await addDoc(collection(db,'villageStories'),common);closeModal('postModal');toast('Story added to the village profile.');if(currentVillage?.id===v.id)renderVillageContent()}catch(err){toast(err.message)}}
async function addVillageMedia(e){e.preventDefault();if(!requireLogin()||!currentVillage)return;try{const media=await uploadMany([...($('moreMedia').files||[])],'villages');const ref=doc(db,'villagesListings',currentVillage.id);const next=[...(currentVillage.media||[]),...media];await updateDoc(ref,{media:next,images:next.filter(x=>x.type==='image').map(x=>x.url),videos:next.filter(x=>x.type==='video').map(x=>x.url),updatedAt:serverTimestamp()});currentVillage={...currentVillage,media:next,images:next.filter(x=>x.type==='image').map(x=>x.url),videos:next.filter(x=>x.type==='video').map(x=>x.url)};villages=villages.map(v=>v.id===currentVillage.id?currentVillage:v);closeModal('mediaModal');renderVillageContent();toast('Media added.')}catch(err){toast(err.message)}}
function openBooking(villageId,activity){if(!requireLogin())return;$('bkVillageId').value=villageId;$('bkActivity').value=activity;openModal('bookingModal')}
async function submitBooking(e){e.preventDefault();if(!requireLogin())return;try{const v=villages.find(x=>x.id===$('bkVillageId').value);await addDoc(collection(db,'bookingInquiries'),{ownerUid:uid(),hostOwnerUid:v?.ownerUid||'',villageId:$('bkVillageId').value,activity:$('bkActivity').value,name:$('bkName').value.trim(),phone:$('bkPhone').value.trim(),date:$('bkDate').value,guests:Number($('bkGuests').value),message:$('bkMessage').value.trim(),status:'new',createdAt:serverTimestamp()});e.target.reset();closeModal('bookingModal');toast('Visit enquiry sent to the host.')}catch(err){toast(err.message)}}
async function loadWeddingEvents(){const c=$('weddingEvents');try{const snap=await getDocs(query(collection(db,'weddingEvents'),orderBy('date','asc')));const events=snap.docs.map(d=>({id:d.id,...d.data()}));c.innerHTML=events.length?events.map(w=>`<article class="village-card"><div class="village-card-body"><div class="location">📍 ${esc(w.villageName)} · ${esc(w.district)}, ${esc(w.state)}</div><h3>${esc(w.title||'Village Wedding Experience')}</h3><p class="muted">${esc(w.description||'A host-listed village wedding experience.')}</p><div class="pill-row"><span class="pill">${esc(w.date||'Date on enquiry')}</span><span class="pill">${w.price?`₹${esc(w.price)}`:'Host priced'}</span></div><div class="card-footer"><span class="muted">Host: ${esc(w.hostName||'Local host')}</span><button class="primary" onclick="enquireWedding('${esc(w.id)}')">Enquire</button></div></div></article>`).join(''):'<div class="empty">No public village wedding experiences listed yet.</div>'}catch(e){c.innerHTML='<div class="empty">Wedding experiences will appear here.</div>'}}
async function enquireWedding(id){if(!requireLogin())return;const name=prompt('Your name');if(!name)return;const phone=prompt('Phone / WhatsApp');if(!phone)return;let hostOwnerUid='';try{const ev=await getDoc(doc(db,'weddingEvents',id));hostOwnerUid=ev.exists()?ev.data().ownerUid||'':''}catch{}await addDoc(collection(db,'weddingInquiries'),{ownerUid:uid(),hostOwnerUid,eventId:id,name,phone,type:'attend-village-wedding',createdAt:serverTimestamp()});toast('Wedding enquiry sent.')}
async function submitDestinationWedding(e){e.preventDefault();if(!requireLogin())return;await addDoc(collection(db,'weddingInquiries'),{ownerUid:uid(),type:'destination-wedding',name:$('dwName').value,phone:$('dwPhone').value,date:$('dwDate').value,guests:Number($('dwGuests').value||0),state:$('dwState').value,message:$('dwMessage').value,createdAt:serverTimestamp()});e.target.reset();toast('Destination wedding enquiry sent.')}
async function loadBusinesses(){const c=$('marketGrid');try{const snap=await getDocs(query(collection(db,'localBusinesses'),orderBy('createdAt','desc')));const bs=snap.docs.map(d=>d.data());if(bs.length)c.innerHTML=bs.map(b=>`<article class="product-card"><span class="product-tag">${esc(b.type)}</span><h3>${esc(b.name)}</h3><p>${esc(b.description)}</p><p><b>📍</b> ${esc(b.village)}, ${esc(b.state)}</p><div class="card-footer"><span class="price">${esc(b.price||'On enquiry')}</span></div></article>`).join('')}catch(e){}}
async function saveBusiness(e){e.preventDefault();if(!requireLogin())return;await addDoc(collection(db,'localBusinesses'),{ownerUid:uid(),name:$('bizName').value,village:$('bizVillage').value,state:$('bizState').value,type:$('bizType').value,price:$('bizPrice').value,description:$('bizDesc').value,createdAt:serverTimestamp()});e.target.reset();closeModal('businessModal');loadMarket();toast('Local business profile added.')}
async function loadMarket(){const c=$('marketGrid');try{const snap=await getDocs(query(collection(db,'products'),orderBy('createdAt','desc')));const ps=snap.docs.map(d=>({id:d.id,...d.data()}));c.innerHTML=ps.length?ps.map(p=>`<article class="product-card">${p.imageUrl?`<img class="product-photo" src="${esc(p.imageUrl)}">`:''}<span class="product-tag">${esc(p.category||'Village Product')}</span><h3>${esc(p.name)}</h3><p>${esc(p.story)}</p><p><b>Grown / made by:</b> ${esc(p.farmer)} · ${esc(p.village)}, ${esc(p.state)}</p><div class="card-footer"><span class="price">₹${esc(p.price)}</span></div></article>`).join(''):'<div class="empty">No village products listed yet.</div>'}try{const bs=(await getDocs(query(collection(db,'localBusinesses'),orderBy('createdAt','desc')))).docs.map(d=>d.data());if(bs.length)c.innerHTML+=bs.map(b=>`<article class="product-card"><span class="product-tag">${esc(b.type)}</span><h3>${esc(b.name)}</h3><p>${esc(b.description)}</p><p><b>📍</b> ${esc(b.village)}, ${esc(b.state)}</p><div class="card-footer"><span class="price">${esc(b.price||'On enquiry')}</span></div></article>`).join('')}catch{} }catch(e){c.innerHTML='<div class="empty">Marketplace could not load.</div>'}}
async function saveProduct(e){e.preventDefault();if(!requireLogin())return;try{const f=$('prMedia').files?.[0];const media=f?await uploadToCloudinary(f,'products'):null;await addDoc(collection(db,'products'),{ownerUid:uid(),name:$('prName').value,farmer:$('prFarmer').value,village:$('prVillage').value,state:$('prState').value,price:Number($('prPrice').value),category:$('prCategory').value,story:$('prStory').value,imageUrl:media?.url||'',createdAt:serverTimestamp()});e.target.reset();closeModal('productModal');loadMarket();toast('Product added to Gaon Ka Bazaar.')}catch(err){toast(err.message)}}
function renderChallenges(){const c=$('challengeGrid');c.innerHTML=CHALLENGES.map(x=>`<article class="challenge-card"><h3>${x[0]} ${x[1]}</h3><p>${x[2]}</p><button class="primary" onclick="openChallenge('${esc(x[1])}')">Submit entry</button></article>`).join('')}
async function openChallenge(title){if(!requireLogin())return;const villageId=prompt('Enter your village document ID');if(!villageId)return;const text=prompt(`Describe your ${title} entry`);if(!text)return;await addDoc(collection(db,'challengeEntries'),{ownerUid:uid(),challenge:title,villageId,text,createdAt:serverTimestamp()});toast('Challenge entry submitted.')}
async function renderProfile(){if(!requireLogin()){showView('homeView');return}const c=$('profileBody');const myVillages=villages.filter(v=>v.ownerUid===uid());let bookings=0,products=0,stories=0;try{bookings=(await getDocs(query(collection(db,'bookingInquiries'),where('ownerUid','==',uid())))).size;products=(await getDocs(query(collection(db,'products'),where('ownerUid','==',uid())))).size;stories=(await getDocs(query(collection(db,'villageStories'),where('ownerUid','==',uid())))).size}catch{}c.innerHTML=`<div class="section-card"><div class="section-grid"><div class="mini-card"><h3>👤 ${esc(currentUser.displayName||'VillageDeko User')}</h3><p>${esc(currentUser.email||'')}</p></div><div class="mini-card"><h3>${myVillages.length}</h3><p>Village listings</p></div><div class="mini-card"><h3>${stories}</h3><p>Stories</p></div><div class="mini-card"><h3>${products}</h3><p>Products</p></div><div class="mini-card"><h3>${bookings}</h3><p>Visit enquiries</p></div></div></div><div class="section-head"><div><h2>Your VillageDeko</h2></div></div><div class="profile-menu"><button class="profile-action" onclick="openListVillage()"><b>🏡 List / manage my village</b><small>Add activities, prices, stay and media.</small></button><button class="profile-action" onclick="openPostModal()"><b>📸 Add village story / media</b><small>Publish to a village profile, not a social feed.</small></button><button class="profile-action" onclick="openProductModal()"><b>🌾 Add village product</b><small>Connect product to farmer and village.</small></button><button class="profile-action" onclick="openWedding()"><b>💍 Weddings</b><small>Attend a village wedding or plan a destination wedding.</small></button><button class="profile-action" onclick="signOutUser()"><b>🚪 Sign out</b></button></div>`}
async function googleLogin(){try{await signInWithPopup(auth,new GoogleAuthProvider());closeModal('loginModal');toast('Signed in successfully.')}catch(e){toast(e.message)}}async function signOutUser(){await signOut(auth);showView('homeView');toast('Signed out')}
function updateAuthUI(){const logged=!!currentUser;$('topAvatar').textContent=logged?(currentUser.displayName||'U').charAt(0).toUpperCase():'👤'}
for(const m of document.querySelectorAll('.modal'))m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)});
window.goHome=goHome;window.openExplore=openExplore;window.openExperience=openExperience;window.openVisit=openVisit;window.openFood=openFood;window.openPeople=openPeople;window.openCulture=openCulture;window.openStories=openStories;window.openFarming=openFarming;window.openMarket=openMarket;window.openChallenges=openChallenges;window.openWedding=openWedding;window.openProfile=openProfile;window.openSearch=openSearch;window.openListVillage=openListVillage;window.openPostModal=openPostModal;window.openMediaUploader=openMediaUploader;window.openProductModal=openProductModal;window.openBusinessModal=openBusinessModal;window.saveBusiness=saveBusiness;window.openModal=openModal;window.closeModal=closeModal;window.selectState=selectState;window.filterVillages=filterVillages;window.openVillage=openVillage;window.setVillageTab=setVillageTab;window.openImage=openImage;window.addActivityRow=addActivityRow;window.addPackageRow=addPackageRow;window.renderActivityRows=renderActivityRows;window.renderPackageRows=renderPackageRows;window.activityRows=activityRows;window.packageRows=packageRows;window.saveVillageListing=saveVillageListing;window.publishVillageContent=publishVillageContent;window.addVillageMedia=addVillageMedia;window.openBooking=openBooking;window.submitBooking=submitBooking;window.submitDestinationWedding=submitDestinationWedding;window.enquireWedding=enquireWedding;window.saveProduct=saveProduct;window.openChallenge=openChallenge;window.signOutUser=signOutUser;
fillStates();renderStates();renderDay();renderFood();renderFarming();renderCulture();renderChallenges();
onAuthStateChanged(auth,async u=>{currentUser=u;updateAuthUI();await loadVillages()});
