(function(){
'use strict';
const safeText=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COMMUNITY_LOCAL='villagedeko_community_posts_v1';
const CHALLENGE_LOCAL='villagedeko_challenge_entries_v1';
let communityFilter='all',communityRemote=[];
const communityCategories={all:'All Knowledge',farming:'Kisan Se Seekho',voice:'Gaon Ki Awaaz',people:'Gaon Ke Log',culture:'Culture & Traditions',knowledge:'Village Knowledge',history:'Old → New',family:'Family Learning'};
function localRows(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(_e){return[]}}
function setLocalRows(key,rows){localStorage.setItem(key,JSON.stringify(rows))}
function listing(v){return v?.listing||v||{}}
function identity(v){return [v?.name||listing(v).villageName,v?.district||listing(v).district,v?.state||listing(v).state].filter(Boolean).join(' · ')}
function mediaMarkup(x){const image=x.image?`<img src="${safeText(x.image)}" alt="${safeText(x.title)}" loading="lazy">`:'',video=x.video?`<video src="${safeText(x.video)}" controls preload="metadata"></video>`:'',audio=x.audio?`<audio src="${safeText(x.audio)}" controls preload="metadata"></audio>`:'';return `<div class="vd-community-media">${image}${video}</div>${audio}`}
function seededCommunity(){const out=[];(window.villages||villages||[]).forEach(v=>{const d=listing(v),where=identity(v),ownerUid=v.ownerUid||d.ownerUid||'';(d.day||[]).filter(x=>x?.[0]).forEach((x,i)=>out.push({id:`day_${v.id}_${i}`,category:'family',title:`${x[0]} — ${x[1]}`,text:x[2],image:x[3],video:x[4],audio:x[5],person:x[6],where,ownerUid,verified:true}));(d.journey||[]).filter(x=>x?.[0]).forEach((x,i)=>out.push({id:`farm_${v.id}_${i}`,category:'farming',title:x[0],text:`${x[1]||'Village'} → ${x[2]||'Plate'} · ${x[3]||''}`,image:x[4],video:x[5],person:x[6],audio:x[7],where,ownerUid,verified:true}));(d.people||[]).filter(x=>x?.[0]).forEach((x,i)=>out.push({id:`people_${v.id}_${i}`,category:'people',title:x[2]||x[0],text:x[3],image:x[4],video:x[5],audio:x[6],person:`${x[0]}${x[1]?` · ${x[1]}`:''}`,where,ownerUid,verified:true}));(d.culture||[]).filter(x=>x?.[0]).forEach((x,i)=>out.push({id:`culture_${v.id}_${i}`,category:'culture',title:x[0],text:x[2],image:x[3],video:x[4],person:x[1],where,ownerUid,verified:true}));(d.food||[]).filter(x=>x?.[0]).forEach((x,i)=>out.push({id:`knowledge_${v.id}_${i}`,category:'knowledge',title:x[0],text:`${x[1]||'Local food'} · ${x[2]||'Village recipe and food knowledge'}`,image:x[3],video:x[4],where,ownerUid,verified:true}));});return out}
function allCommunity(){const map=new Map();[...seededCommunity(),...localRows(COMMUNITY_LOCAL),...communityRemote].forEach(x=>map.set(x.id,x));return [...map.values()].sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0))}
function ensureCommunityNav(){const desktop=document.querySelector('.desktop-nav'),mobile=document.querySelector('.bottom-nav');if(desktop&&!desktop.querySelector('[data-nav="slide-community"]')){const market=desktop.querySelector('[data-nav="slide-market"]')||desktop.querySelector('[data-nav="slide-stories"]'),b=document.createElement('button');b.className='desktop-nav-item';b.dataset.nav='slide-community';b.textContent='Community';desktop.insertBefore(b,market)}if(mobile&&!mobile.querySelector('[data-nav="slide-community"]')){const market=mobile.querySelector('[data-nav="slide-market"]')||mobile.querySelector('[data-nav="slide-stories"]'),b=document.createElement('button');b.className='nav-item';b.dataset.nav='slide-community';b.setAttribute('aria-label','Community');b.innerHTML='<span class="nav-icon" aria-hidden="true">🤝</span><span>Community</span>';mobile.insertBefore(b,market)}}
function ensureCommunitySlide(){if(document.getElementById('slide-community'))return;const s=document.createElement('section');s.id='slide-community';s.className='content-slide slide vd-community-slide';s.innerHTML='<div id="vd-community-root"></div>';document.querySelector('main')?.appendChild(s)}
function showCommunitySlide(){document.querySelectorAll('.slide').forEach(s=>{const active=s.id==='slide-community';s.classList.toggle('active',active);s.hidden=!active;s.setAttribute('aria-hidden',active?'false':'true');s.style.setProperty('display',active?'block':'none','important')});const feed=document.getElementById('home-village-feed');if(feed)feed.style.display='none';document.querySelectorAll('.nav-item,.desktop-nav-item').forEach(n=>{const active=n.dataset.nav==='slide-community';n.classList.toggle('active',active);n.setAttribute('aria-current',active?'page':'false')});window.scrollTo({top:0,behavior:'auto'})}
function hideCommunitySlide(){const s=document.getElementById('slide-community');if(s){s.classList.remove('active');s.hidden=true;s.style.setProperty('display','none','important')}}
function familyPackages(){const rows=[];(window.villages||villages||[]).forEach(v=>(listing(v).package||[]).filter(x=>x?.[0]).forEach((x,i)=>rows.push({v,index:i,x})));return rows.slice(0,6)}
function challengeEntries(){return localRows(CHALLENGE_LOCAL)}
function renderCommunity(){ensureCommunitySlide();const root=document.getElementById('vd-community-root');if(!root)return;const rows=allCommunity().filter(x=>communityFilter==='all'||x.category===communityFilter),packages=familyPackages(),entries=challengeEntries();root.innerHTML=`
  <section class="vd-community-hero"><div><small>VILLAGE KNOWLEDGE & CULTURE</small><h1>Gaon se seekho.<br>Gaon ki awaaz suno.</h1><p>Real farmers, local people, folk audio, traditions, family learning aur village knowledge — village identity ke saath.</p><div class="vd-community-actions"><button class="primary" data-action="community-contribute">+ Share Village Knowledge</button><button class="secondary" data-action="community-challenge-form">🏆 Join Challenge</button></div></div><div class="vd-community-hero-art">🎙️<span>🌾</span><b>🤝</b></div></section>
  <section class="vd-ecosystem"><small>VILLAGEDEKO JOURNEY</small><div>${[['🗺️','Discover'],['👨‍🌾','People'],['🌅','Village Life'],['🌾','Food'],['🎵','Culture'],['🤝','Community'],['🧳','Visit'],['🛒','Market']].map(x=>`<button data-action="community-journey" data-target="${x[1]}"><span>${x[0]}</span><b>${x[1]}</b></button>`).join('<i>→</i>')}</div></section>
  <section><div class="vd-community-head"><div><small>LEARN · LISTEN · PRESERVE</small><h2>Community Knowledge</h2></div><strong>${rows.length} stories</strong></div><div class="vd-community-filters">${Object.entries(communityCategories).map(([k,v])=>`<button class="${communityFilter===k?'active':''}" data-action="community-filter" data-category="${k}">${v}</button>`).join('')}</div><div class="vd-community-grid">${rows.length?rows.map(x=>`<article class="vd-community-card">${mediaMarkup(x)}<div><small>${safeText(communityCategories[x.category]||'Village Knowledge')} ${x.verified?'· ✓ VILLAGE SOURCE':''}</small><h3>${safeText(x.title)}</h3>${x.person?`<b>👤 ${safeText(x.person)}</b>`:''}<p>${safeText(x.text||'')}</p><span>📍 ${safeText(x.where||'Village · District · State')}</span>${x.language?`<em>🗣️ ${safeText(x.language)}</em>`:''}</div></article>`).join(''):'<div class="vd-community-empty">Is category mein host ka real village content aate hi yahan dikhega.</div>'}</div></section>
  <section class="vd-family-section"><div class="vd-community-head"><div><small>FAMILY VILLAGE EXPERIENCE</small><h2>Bachchon ko asli gaon dikhaiye</h2><p>Beej → Khet → Farmer → Doodh → Local Food → Culture</p></div></div><div class="vd-family-grid">${packages.length?packages.map(({v,index,x})=>`<article>${x[13]?`<img src="${safeText(x[13])}" alt="${safeText(x[0])}">`:''}<div><small>👨‍👩‍👧 FAMILY LEARNING</small><h3>${safeText(x[0])}</h3><p>${safeText(x[2]||x[3]||'Complete village learning experience')}</p><b>📍 ${safeText(identity(v))}</b><button class="primary" data-action="community-package" data-village="${safeText(v.id)}" data-index="${index}">View & Add Package</button></div></article>`).join(''):'<p class="vd-community-empty">Host ka family package publish hote hi yahan aayega.</p>'}</div></section>
  <section class="vd-challenges"><div class="vd-community-head"><div><small>SEASONAL VILLAGE CHALLENGES</small><h2>Quality aur originality ki pehchaan</h2></div><button class="primary" data-action="community-challenge-form">Submit Entry</button></div><div class="vd-challenge-grid">${[['🌅','Best Village Sunrise'],['🌾','Best Farming Story'],['🍲','Best Local Food'],['🎵','Best Folk Culture'],['📸','Old vs New Village'],['🎉','Best Festival Story']].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>Likes ki race nahi—village value, originality aur real context important hai.</p></article>`).join('')}</div>${entries.length?`<div class="vd-entry-strip"><strong>${entries.length} community challenge entries</strong>${entries.slice(-4).map(x=>`<span>${safeText(x.title)} · ${safeText(x.where)}</span>`).join('')}</div>`:''}</section>
  <section class="vd-community-principle"><span>❤️</span><div><small>VILLAGE-FIRST BUSINESS PRINCIPLE</small><h2>Useful + Trusted, phir monetization</h2><p>Stay, experiences, local guide aur marketplace se aane wali value village ecosystem ko benefit karegi. Random ads se village experience kharab nahi hoga.</p><button class="secondary" data-nav="slide-market">Open Story-led Village Market →</button></div></section>`}
async function loadCommunityRemote(){if(!window.firestoreDb&&!firestoreDb)return;try{const db=window.firestoreDb||firestoreDb,q=window.VD_FIREBASE.query(window.VD_FIREBASE.collection(db,'communityPosts')),snap=await window.VD_FIREBASE.getDocs(q);communityRemote=snap.docs.map(d=>d.data());renderCommunity()}catch(e){console.warn('Community sync skipped',e)}}
function openContributionForm(){if(typeof requireGoogleAuth==='function'&&!firebaseUser){requireGoogleAuth();return}openModal('Share Village Knowledge',`<div class="vd-community-form"><p class="form-note">Sirf real village knowledge, farming, culture, people aur local audio share karein.</p><label>Category<select id="vd-community-category"><option value="farming">Kisan Se Seekho</option><option value="voice">Gaon Ki Awaaz / Folk Audio</option><option value="people">Gaon Ke Log</option><option value="culture">Culture & Traditions</option><option value="knowledge">Village Knowledge</option><option value="history">Old → New Village</option><option value="family">Family Learning</option></select></label><label>Title<input id="vd-community-title" maxlength="120" placeholder="Real village topic"></label><label>Person name & role<input id="vd-community-person" maxlength="100" placeholder="Ramesh ji · Farmer"></label><label>Explanation / story<textarea id="vd-community-text" rows="5" maxlength="1500"></textarea></label><label>Language<input id="vd-community-language" maxlength="50" placeholder="Hindi / Marwari / Punjabi..."></label><label>Photo (optional)<input id="vd-community-image" type="file" accept="image/*"></label><label>Video (optional)<input id="vd-community-video" type="file" accept="video/*"></label><label>Local voice / folk audio (optional)<input id="vd-community-audio" type="file" accept="audio/*"></label><div class="menu-actions"><button class="secondary" data-action="close">Cancel</button><button class="primary" data-action="community-publish">Publish to Community</button></div></div>`)}
async function publishCommunity(){if(!(await requireGoogleAuth()))return;const title=document.getElementById('vd-community-title')?.value.trim(),text=document.getElementById('vd-community-text')?.value.trim();if(!title||!text){openModal('Information required','Title aur explanation dono add karein.');return}const village=(villages||[]).find(v=>v.ownerUid===firebaseUser.uid||v.id==='my-listing'),d=listing(village),files={image:document.getElementById('vd-community-image')?.files?.[0],video:document.getElementById('vd-community-video')?.files?.[0],audio:document.getElementById('vd-community-audio')?.files?.[0]},uploaded={};try{for(const [k,f] of Object.entries(files))if(f)uploaded[k]=await uploadCloudinary(f)}catch(e){openModal('Media upload failed',e?.message||'Please try again.');return}const post={id:`community_${firebaseUser.uid}_${Date.now()}`,uid:firebaseUser.uid,ownerUid:firebaseUser.uid,category:document.getElementById('vd-community-category').value,title,text,person:document.getElementById('vd-community-person').value.trim(),language:document.getElementById('vd-community-language').value.trim(),image:uploaded.image||'',video:uploaded.video||'',audio:uploaded.audio||'',villageId:village?.id||firebaseUser.uid,where:village?identity(village):[d.villageName,d.district,d.state].filter(Boolean).join(' · '),verified:Boolean(village),createdAt:Date.now()};setLocalRows(COMMUNITY_LOCAL,[...localRows(COMMUNITY_LOCAL),post]);if(firestoreDb)try{await window.VD_FIREBASE.setDoc(window.VD_FIREBASE.doc(firestoreDb,'communityPosts',post.id),post)}catch(e){console.warn('Community remote save failed',e)}closeModal();communityFilter='all';renderCommunity();showSlide('slide-community')}
function openChallengeForm(){openModal('Village Challenge Entry',`<div class="vd-community-form"><label>Challenge<select id="vd-challenge-name"><option>Best Village Sunrise</option><option>Best Farming Story</option><option>Best Local Food</option><option>Best Folk Culture</option><option>Old vs New Village</option><option>Best Festival Story</option></select></label><label>Entry title<input id="vd-challenge-title" maxlength="120"></label><label>Why is it valuable?<textarea id="vd-challenge-story" rows="4" maxlength="800"></textarea></label><div class="menu-actions"><button class="secondary" data-action="close">Cancel</button><button class="primary" data-action="community-challenge-save">Submit Entry</button></div></div>`)}
function saveChallenge(){const title=document.getElementById('vd-challenge-title')?.value.trim(),story=document.getElementById('vd-challenge-story')?.value.trim();if(!title||!story)return;const v=currentVillage||villages?.[0],row={id:`challenge_${Date.now()}`,challenge:document.getElementById('vd-challenge-name').value,title,story,where:identity(v),createdAt:Date.now()};setLocalRows(CHALLENGE_LOCAL,[...challengeEntries(),row]);closeModal();renderCommunity();showSlide('slide-community')}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action],[data-nav]');if(!el)return;if(el.dataset.nav==='slide-community'){setTimeout(()=>{renderCommunity();showCommunitySlide();loadCommunityRemote()},0);return}if(el.dataset.nav)hideCommunitySlide();const a=el.dataset.action;if(a==='community-filter'){communityFilter=el.dataset.category||'all';renderCommunity();return}if(a==='community-contribute'){openContributionForm();return}if(a==='community-publish'){await publishCommunity();return}if(a==='community-challenge-form'){openChallengeForm();return}if(a==='community-challenge-save'){saveChallenge();return}if(a==='community-package'){const v=villages.find(x=>x.id===el.dataset.village);if(v){hideCommunitySlide();setCurrentVillage(v);openVillageBooking(Number(el.dataset.index||0))}return}if(a==='community-journey'){const target=el.dataset.target;if(target==='Discover'){hideCommunitySlide();showSlide('slide-explore')}else if(target==='Market'){hideCommunitySlide();showSlide('slide-market');renderMarket()}else{communityFilter=target==='People'?'people':target==='Food'?'farming':target==='Culture'?'culture':'all';renderCommunity();showCommunitySlide()}return}},true);
ensureCommunitySlide();ensureCommunityNav();try{renderCommunity()}catch(e){console.error('Community render failed',e);const root=document.getElementById('vd-community-root');if(root)root.innerHTML=`<pre class="vd-community-empty">${safeText(e?.stack||e?.message||e)}</pre>`}setTimeout(loadCommunityRemote,1600);
new MutationObserver(()=>ensureCommunityNav()).observe(document.body,{childList:true,subtree:true});
})();
